/**
 * ASMREF JSON module for assembly reference lookups.
 *
 * Provides fast lookups for assembly-to-component mappings with Onshape IDs.
 * Used during assembly relink to determine whether to:
 *   - Replace instance with master part (has IDs)
 *   - Keep local and set properties (virtual part or pending subassembly)
 *
 * JSON structure (generated by convertAsmrefToJson.js):
 *   byAssembly: { ASSEMBLY.SLDASM: { COMPONENT.SLDPRT: { documentId, ... } } }
 *   byPartNumber: { partNumber: [assemblyNames...] }
 *   metadata: { generated, sourceFile, rowCount, ... }
 */

const fs = require('fs');

/**
 * Load ASMREF JSON file.
 * @param {string} jsonPath - Path to asmref.json
 * @returns {Object} Loaded data object or null if not found
 */
function load(jsonPath) {
  if (!fs.existsSync(jsonPath)) {
    console.warn(`ASMREF file not found: ${jsonPath}`);
    return null;
  }

  try {
    const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    console.log(`ASMREF loaded: ${data.metadata?.uniqueEntries || 0} entries from ${data.metadata?.assemblies || 0} assemblies`);
    return data;
  } catch (err) {
    console.error(`Failed to load ASMREF: ${err.message}`);
    return null;
  }
}

/**
 * Extract base part number from a filename, stripping extension and configuration suffix.
 * E.g., "30093_[30093-01].SLDPRT" -> "30093"
 *       "51298.SLDPRT" -> "51298"
 *       "PART_[Config-A].SLDPRT" -> "PART"
 *
 * @param {string} filename - Filename to extract base from
 * @returns {string} Base part number (uppercase)
 */
function extractBaseName(filename) {
  let name = filename.toUpperCase().trim();
  // Remove extension
  name = name.replace(/\.SLDPRT$/i, '').replace(/\.SLDASM$/i, '');
  // Remove configuration suffix like _[config-name] or _[CONFIG]
  name = name.replace(/_\[[^\]]+\]$/, '');
  return name;
}

/**
 * Lookup an entry for a specific assembly + component combination.
 * Case-insensitive matching on both assembly and link file names.
 * Handles configuration suffixes (e.g., "30093_[30093-01].SLDPRT" matches instance "30093").
 *
 * @param {Object} data - ASMREF data object from load()
 * @param {string} assemblyName - Assembly filename (e.g., "100002.SLDASM" or "100002")
 * @param {string} linkFileName - Component filename (e.g., "51298.SLDPRT" or "51298")
 * @returns {Object|null} Entry with { documentId, workspaceId, elementId, versionId, isVirtual, type, properties } or null
 */
function lookup(data, assemblyName, linkFileName) {
  if (!data || !data.byAssembly) {
    return null;
  }

  // Normalize inputs to uppercase
  let asmKey = assemblyName.toUpperCase().trim();
  let linkKey = linkFileName.toUpperCase().trim();

  // Ensure assembly key has extension
  if (!asmKey.endsWith('.SLDASM')) {
    asmKey = asmKey + '.SLDASM';
  }

  // Extract base name from the search key (strip extension and any config suffix)
  const searchBase = extractBaseName(linkKey);

  const components = data.byAssembly[asmKey];
  if (components) {
    // Try exact match first
    if (components[linkKey]) {
      return components[linkKey];
    }

    // Search for matching entry by comparing base names
    for (const key in components) {
      // Exact key match (already tried above)
      if (key === linkKey) continue;

      // Compare base names (handles config suffixes like _[30093-01])
      const keyBase = extractBaseName(key);
      if (keyBase === searchBase) {
        return components[key];
      }
    }
  }

  // Cross-assembly fallback: search all other assemblies for the same component
  for (const otherAsm in data.byAssembly) {
    if (otherAsm === asmKey) continue;
    const otherComponents = data.byAssembly[otherAsm];

    // Exact match
    if (otherComponents[linkKey]) {
      return otherComponents[linkKey];
    }

    // Base name match
    for (const key in otherComponents) {
      if (extractBaseName(key) === searchBase) {
        return otherComponents[key];
      }
    }
  }

  return null;
}

/**
 * Update all entries with a given part number to have new Onshape IDs.
 * Used after releasing an assembly/part to backfill IDs for sub-assembly references.
 *
 * @param {Object} data - ASMREF data object
 * @param {string} partNumber - Part number to update
 * @param {Object} ids - { documentId, workspaceId, elementId, versionId }
 * @returns {number} Number of entries updated
 */
function updateIds(data, partNumber, ids) {
  if (!data || !data.byPartNumber || !partNumber) {
    return 0;
  }

  const assemblies = data.byPartNumber[partNumber];
  if (!assemblies || assemblies.length === 0) {
    return 0;
  }

  let updateCount = 0;

  assemblies.forEach(asmKey => {
    if (!data.byAssembly[asmKey]) return;

    // Find entries matching this part number
    for (const linkKey in data.byAssembly[asmKey]) {
      const entry = data.byAssembly[asmKey][linkKey];
      if (entry.partNumber === partNumber) {
        // Update IDs
        entry.documentId = ids.documentId || entry.documentId;
        entry.workspaceId = ids.workspaceId || entry.workspaceId;
        entry.elementId = ids.elementId || entry.elementId;
        entry.versionId = ids.versionId || entry.versionId;
        updateCount++;
      }
    }
  });

  return updateCount;
}

/**
 * Save ASMREF data to JSON file.
 * Should be called after updateIds() to persist changes.
 *
 * @param {Object} data - ASMREF data object
 * @param {string} jsonPath - Path to save to
 */
function save(data, jsonPath) {
  if (!data) {
    console.warn('No ASMREF data to save');
    return;
  }

  data.metadata = data.metadata || {};
  data.metadata.lastUpdated = new Date().toISOString();

  fs.writeFileSync(jsonPath, JSON.stringify(data, null, 2));
}

/**
 * Get all component entries for an assembly.
 * Useful for debugging and validation.
 *
 * @param {Object} data - ASMREF data object
 * @param {string} assemblyName - Assembly filename
 * @returns {Object} Map of linkFileName -> entry
 */
function getAssemblyComponents(data, assemblyName) {
  if (!data || !data.byAssembly) {
    return {};
  }

  let asmKey = assemblyName.toUpperCase().trim();
  if (!asmKey.endsWith('.SLDASM')) {
    asmKey = asmKey + '.SLDASM';
  }

  return data.byAssembly[asmKey] || {};
}

/**
 * Get statistics about ASMREF data.
 *
 * @param {Object} data - ASMREF data object
 * @returns {Object} Stats object
 */
function getStats(data) {
  if (!data) {
    return { error: 'No data loaded' };
  }

  let withIds = 0;
  let withoutIds = 0;
  let virtualParts = 0;
  let subassemblies = 0;

  for (const asmKey in data.byAssembly) {
    for (const linkKey in data.byAssembly[asmKey]) {
      const entry = data.byAssembly[asmKey][linkKey];
      if (entry.documentId) {
        withIds++;
      } else {
        withoutIds++;
      }
      if (entry.isVirtual) {
        virtualParts++;
      }
      if (entry.type === 'SLDASM') {
        subassemblies++;
      }
    }
  }

  return {
    assemblies: Object.keys(data.byAssembly).length,
    uniqueEntries: withIds + withoutIds,
    withIds,
    withoutIds,
    virtualParts,
    subassemblies,
    metadata: data.metadata
  };
}

module.exports = {
  load,
  lookup,
  updateIds,
  save,
  getAssemblyComponents,
  getStats
};
